# Gains for MPC
/**:
  ros__parameters:
    path_tracker:
      ## Scheduled speed based on curvatures: if curv[vertex_number] > thresh[i], take speed [i]
      curvature_thresholds: [0.0, 1.5, 3.0, 10.0, 40.0]
      target_linear_speed: [0.5, 0.51, 0.52, 0.53, 1.0]

      ## Controller gains (for feedback linearization mostly)
      look_ahead_distance: [0.5, 0.51, 0.52, 0.53, 1.0]
      angular_look_ahead: [0.3, 0.3, 0.3, 0.3, 0.3]
      heading_error_gain: [0.75, 0.75, 0.75, 0.75, 0.75]
      lateral_error_gain: [0.3, 0.3, 0.3, 0.3, 0.3]

      saturation_limit: [2.0, 2.0, 2.0, 2.0, 2.0]
