/**:
  ros__parameters:
    ############ system configuration ############

    # The lidar frame from the urdf (also defines the rig name)
    lidar_frame: honeycomb
    # The control frame from the urdf
    robot_frame: base_link

    ############ map projection configuration ############
    map_projection:
      origin_lat: 43.78220
      origin_lng: -79.4661
      origin_theta: 1.3 # positive == clockwise
      scale: 1.0

    ############ tactic configuration ############
    tactic:
      visualize: true

    ############ pipeline configuration ############
    pipeline:
      # pipeline parameters
      map_voxel_size: 0.2

    preprocessing:
      preprocessing:
        num_channels: 128
        vertical_angle_res: 0.0132645
        polar_r_scale: 2.0
        r_scale: 2.0
        h_scale: 2.0
        num_sample1: 10000
        min_norm_score1: 0.5

        num_sample2: 10000
        min_norm_score2: 0.01 # 0.2 is where 5/12 * pi
        ideal_normal_estimate_dist: 2.0

        cluster_num_sample: 10000

        frame_voxel_size: 0.1
        visualize: true

    odometry:
      recall:
        type: "lidar.map_recall"
        map_voxel_size: 0.2
        visualize: true

      icp:
        trajectory_smoothing: true
        use_constant_acc: false
        lin_acc_std_dev_x: 1.0
        lin_acc_std_dev_y: 0.1
        lin_acc_std_dev_z: 0.1
        ang_acc_std_dev_x: 0.1
        ang_acc_std_dev_y: 0.1
        ang_acc_std_dev_z: 1.0

        # ICP parameters
        num_threads: 12
        initial_max_iter: 10
        initial_num_samples: 1000
        initial_max_pairing_dist: 1.0
        initial_max_planar_dist: 0.3
        refined_max_iter: 50
        refined_num_samples: 12000
        refined_max_pairing_dist: 1.0
        refined_max_planar_dist: 0.1

        min_matched_ratio: 0.4

      mapping:
        map_voxel_size: 0.2

        # dynamic objects removal
        horizontal_resolution: 0.01
        vertical_resolution: 0.01
        min_num_observations: 1
        max_num_observations: 20

      keyframe_test:
        min_translation: 1.0 # 2
        min_rotation: 15.0
        max_translation: 3.0 # 6
        max_rotation: 30.0 # 45

        min_matched_points_ratio: 0.5 # 0.35

        max_num_points: 100000

    localization:
      recall:
        single_exp_map_voxel_size: 0.2
        multi_exp_map_voxel_size: 0.3
        depth: 3
        num_additional_exps: 2
        remove_short_term_dynamic: false
        visualize: true

      icp:
        use_pose_prior: true

        # ICP parameters
        num_threads: 12
        initial_max_iter: 10
        initial_num_samples: 1000
        initial_max_pairing_dist: 1.0
        initial_max_planar_dist: 0.3
        refined_max_iter: 50
        refined_num_samples: 12000
        refined_max_pairing_dist: 1.0
        refined_max_planar_dist: 0.1

        min_matched_ratio: 0.4
